### ISSUE TITLE
Could not find a package configuration file provided by "PCL" ubuntu 19.04

### ISSUE THREAD

**Issue by IbrahimOmar91** [udacity/SFND_Lidar_Obstacle_Detection#14]
### I am having this error when i try to compile the project on ubuntu 19.04

`CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" (requested
  version 1.2) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/hema/SFND/01Lidar/SFND_Lidar_Obstacle_Detection/build/CMakeFiles/CMakeOutput.log".`

**Comment by roman-smirnov** [comment]
Hi! send me a message on Udacity study hall, we'll solve your issue together!

**Comment by IbrahimOmar91** [comment]
After help from roman, now it is working re-cloning the Repository in case anyone had the same issue

**Comment by MallakAbunimeh** [comment]
I also faced the same issue on raspberry pi after running catkin_make:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/114362747/235469969-ddd29942-5eec-4ee6-8bac-f9deff1208fe.png">

Can you also assist me in solving it? @roman-smirnov
