### ISSUE TITLE
Helpful link for someone who meet error below.

### ISSUE THREAD

**Issue by DonghunP** [udacity/SFND_Lidar_Obstacle_Detection#16]
1. **' "/usr/lib/x86_64-linux-gnu/libEGL.so" but this file does not exist' error**
`sudo rm /usr/lib/x86_64-linux-gnu/libEGL.so; sudo ln /usr/lib/x86_64-linux-gnu/libEGL.so.1 /usr/lib/x86_64-linux-gnu/libEGL.so`

  
2. **When you met an error below during 'make'**
*** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so'
--> [link](https://stackoverflow.com/questions/37369369/compiling-pcl-1-7-on-ubuntu-16-04-errors-in-cmake-generated-makefile)

**Comment by ZmeiGorynych** [comment]
Thanks! I also had to do 
```
sudo rm /usr/lib/x86_64-linux-gnu/libGL.so; sudo ln /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so
```
then `cmake ..` completed without errors.

**Comment by ZmeiGorynych** [comment]
And for the second error, the link you kindly included contains a fair amount of info, summary for the impatient: to fix error 2., run `sudo apt install libproj-dev`
Worked for me - thanks @DonghunP !

**Comment by sandropapais** [comment]
Error 2 fix suggested by @DonghunP  worked for me on ubuntu 16.04. Some additional errors I had during 'make':

**3. No package libopenni2 found** (even though I had built OpenNI2 already)
Sudo apt-get install the following: 
openni2-doc 
openni2-utils 
openni-doc 
openni-utils
libopenni0 libopenni-sensor-pointclouds0
libopenni2-0 libopenni-sensor-pointclouds-dev
libopenni2-dev
Libopenni-dev

**4. The imported target "vtkRenderingPythonTkWidgets" references the file "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so" but this file does not exist.**
sudo ln -s /usr/lib/python2.7/dist-packages/vtk/libvtkRenderingPythonTkWidgets.x86_64-linux-gnu.so /usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so

source: https://github.com/Autoware-AI/autoware.ai/issues/1072
