### ISSUE TITLE
PCL installed with Homebrew

### ISSUE THREAD

**Issue by alvgaona** [udacity/SFND_Lidar_Obstacle_Detection#23]
As at now, Homebrew provides PCL version 1.9.1. However, this version has a bug which makes the project fail at compile time. 

The fix is, once installed via Hombrew, go to this [file](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/common/include/pcl/impl/point_types.hpp) in your local machine and modify this [line](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/common/include/pcl/impl/point_types.hpp#L697) so it looks like this other [one](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.10.0/common/include/pcl/impl/point_types.hpp#L687).

Probably, adding the link to this issue into the README would help students.

Feel free to close it.

Alvaro

**Comment by ray-phan-oxb** [comment]
I also have version 1.9.1 installed via Homebrew on Catalina and it does not fail at compile time for me.   It might be due to the Xcode build tools recently being updated.  Just commenting that I have not been able to reproduce this.

**Comment by rayryeng** [comment]
I also have version 1.9.1 installed via Homebrew on Catalina and it does not fail at compile time for me.   It might be due to the Xcode build tools recently being updated.  Just commenting that I have not been able to reproduce this.
