### ISSUE TITLE
PCL 1.2 & C++ 14 or Above

### ISSUE THREAD

**Issue by whittenator** [udacity/SFND_Lidar_Obstacle_Detection#30]
When building this the cmake requires PCL version 1.2 which requires C++ 14 or above now. In the Cmake the following line needed to be changed for me: 
```
add_definitions(-std=c++14)
```

**Comment by castarco** [comment]
Hi, I'm another student. Did you sent a patch as a pull request to this repository?

**Comment by abhiojha8** [comment]
We have added further instructions in the README that will help in installing the latest version of PCL locally and use C++14.  Closing this issue now.
