### ISSUE TITLE
Updated link to PCL on Windows

### ISSUE THREAD

**Issue by ericwilliamsneu** [udacity/SFND_Lidar_Obstacle_Detection#32]
Hi Udacity Sensor Fusion team - it looks like the ReadMe startup guide has a broken link for the Windows setup of the Point Cloud Library. The existing link results in a 404 not found at pointclouds.org. Could the link be updated with the "Cross Platform" setup instructions here: [PCL Cross-Platform](https://pointclouds.org/downloads/#cross-platform).

**Comment by abhiojha8** [comment]
Thanks! We have updated the link.
