### ISSUE TITLE
apt repository libpcl-dev version missmatch for Ubuntu

### ISSUE THREAD

**Issue by logicatcore** [udacity/SFND_Lidar_Obstacle_Detection#40]
The local installation instructions for Ubuntu instruct to set the required PCL library to version 1.11, but currently, the library version being distributed by the apt repository for 18.04 and 20.04 are both older than this. The following links have the information regarding the versions-

- Bionic 18.04 -->  https://www.ubuntuupdates.org/package/core/bionic/universe/updates/libpcl-dev
- Focal 20.04  -->  https://www.ubuntuupdates.org/package/core/focal/universe/base/libpcl-dev

If I am not missing anything here, an update to the local installation instructions might be useful for future students.

**Comment by abhiojha8** [comment]
Thanks! Added a note in the README. We will further update this once we refresh the classroom workspace.
