### ISSUE TITLE
Build error on Mac

### ISSUE THREAD

**Issue by hariperla** [udacity/SFND_Lidar_Obstacle_Detection#45]
Followed the steps to setup the required packages and cloned the repo. When I tried to build, I get the following dependency error and I am not sure what's the cause. 

<img width="1236" alt="Screen Shot 2022-02-16 at 8 34 23 AM" src="https://user-images.githubusercontent.com/40438231/154275404-6c642dde-8830-4326-b5b5-b5d2bb4186db.png">

**Comment by hariperla** [comment]
<img width="625" alt="Screen Shot 2022-02-16 at 8 35 11 AM" src="https://user-images.githubusercontent.com/40438231/154275559-dc0d3976-c4cf-449d-9341-1069827025ab.png">

**Comment by ameyk1** [comment]
The error is related to Qt5; 

First check if qt@5 is installed with pcl:
`brew info pcl`

Following command worked for me:
```
QT5_DIR=$(brew info qt5 | grep "^$(brew --cellar qt5)" | cut -d' ' -f1)
cmake .. ... -DCMAKE_PREFIX_PATH=$QT5_DIR/
```


Check here for more comments: https://github.com/Cockatrice/Cockatrice/issues/205#issuecomment-183087315

**Comment by elros88** [comment]
I got the same error. I installed Qt5.15 using the online installer and have Python3.9 and Anaconda installed. I had to set the path for Qt5 and Python in bash_profile to solve the error. This is how my bash_profile file looks:
`PATH=dir_where_qt_is_installed/5.15.2/clang_64/bin:$PATH
export PATH
PYTHONPATH="/usr/local/bin/python3"
export PYTHONPATH`

hope this helps
