### ISSUE TITLE
Add destructors to KdTree and Node

### ISSUE THREAD

**Issue by mike239x** [udacity/SFND_Lidar_Obstacle_Detection#9]
Both Node and KdTree have pointers to Nodes, which I believe wont be deleted by an unaware programmer. I suggest adding destructors to those two classes where the corresponding pointers would be deleted.

**Comment by ray-phan-oxb** [comment]
This is not correct - you would be deleting the root node but you wouldn't be deleting all of the other children node that are leaves to the root node.  You would need to delete all the nodes recursively.  Thankfully, this is a binary search tree so you can do this quite easily: https://www.geeksforgeeks.org/deletion-binary-tree/

**Comment by rayryeng** [comment]
This is not correct - you would be deleting the root node but you wouldn't be deleting all of the other children node that are leaves to the root node. You would need to delete all the nodes recursively. Thankfully, this is a binary search tree so you can do this quite easily: https://www.geeksforgeeks.org/deletion-binary-tree/

**Comment by abhiojha8** [comment]
This is now resolved.
